spring:
  application:
    name: employee-service
  data:
    mongodb:
      authentication-database: admin
      username: kanatera
      password: rafael1978
      database: app_db
      port: 27017
      host: 192.168.7.17

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka

management:
  endpoints:
    web:
      exposure:
        include:
        - metrics
        - prometheus
