server:
  #port: 0
  port: 8081

spring:
  zipkin:
    baseUrl: http://192.168.7.17:9411
  application:
    name: employee-service
  cloud:
    config:
      override-system-properties: true
      allow-override: true
      override-none: true
  sleuth:
    sampler:
      probability: 1.0
  data:
    mongodb:
      authentication-database: admin
      username: kanatera
      password: rafael1978
      database: app_db
      port: 27017
      host: 192.168.7.17

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka

management:
  endpoints:
    web:
      exposure:
        include:
        - metrics
        - prometheus
