server:
  port: 8080

spring:
  application:
    name: gateway-proxy
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employees/**
        - id: department-service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
        - id: organization-service
          uri: lb://ORGANIZATION-SERVICE
          predicates:
            - Path=/organizations/**



#zuul:
#  #prefix: /api
#  ignoredServices: '*'
#  routes:
#    employee-service:
#      path: /employees/**
#      serviceId: employee-service
#     employee-service:
#       path: /employees/**
#       stripPrefix: false
#     department-service:
#       path: /departments/**
#       stripPrefix: false
#     organization-service:
#       path: /organizations/**
#       stripPrefix: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
